apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "devops-agent.fullname" . }}
  labels:
{{ include "devops-agent.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "devops-agent.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "devops-agent.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
          - name: DOCKER_HOST
            value: tcp://localhost:2375
          - name: AZP_URL
            value: "{{ .Values.azdevops.azpUrl }}"
          - name: AZP_TOKEN
            value: "{{ .Values.azdevops.azpToken }}"
          - name: AZP_POOL
            value: "{{ .Values.azdevops.azpPool }}"
          - name: AZP_AGENT_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: trivy-cache
            mountPath: /root/.cache
          securityContext:
            privileged: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: dind
          image: "{{ .Values.docker.image.repository }}:{{ .Values.docker.image.tag }}"
          securityContext:
            privileged: true
          env:
          - name: DOCKER_TLS_CERTDIR
            value: ''
          volumeMounts:
          - name: dind-storage
            mountPath: /var/lib/docker
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: trivy-cache
          hostPath:
            path: /var/trivy/Library/Caches
            type: DirectoryOrCreate
  volumeClaimTemplates:
  - metadata:
      name: dind-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Delete
